version: "3"

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=example
    networks:
      - net-dev
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /mnt/dev-data/db/mysql-data:/var/lib/mysql
      - /mnt/dev-data/db/mysql.conf.d:/etc/mysql/mysql.conf.d

  redis:
    image: redis:5.0.5
    container_name: redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass example
    ports:
      - "6379:6379"
    networks:
      - net-dev
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
      - /mnt/dev-data/db/redis-data:/data

  mongo:
    image: mongo:4
    restart: unless-stopped
    ports:
      - "27017:27017"
    networks:
      - net-dev
    volumes:
      - /mnt/dev-data/db/mongo-data:/data/db

  mongo-express:
    image: mongo-express:0.54
    restart: unless-stopped
    ports:
      - "27081:8081"
    networks:
      - net-dev

networks:
  net-dev:
    external: true
